on:
  release:
    types:
      - published

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3

      - name: Deps
        run: |
          sudo apt install -y nettle-dev

      - name: publish to crates.io
        run: |
          echo ${{ secrets.CRATES_IO_TOKEN }} | cargo login
          cargo publish
